name: Pull-Request
on:
  pull_request:

jobs:
  valgrind:
    needs: ['cpp-lint', 'js-lint']
    strategy:
      matrix:
        version: [18, 19, 20, 21, 22, 23, 24, 25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.version }}
      - run: sudo apt-get update && sudo apt-get install valgrind
      - run: npm i --ignore-scripts
      - run: npm run test:js-valgrind

  asan:
    needs: ['cpp-lint', 'js-lint']
    strategy:
      matrix:
        version: [18, 19, 20, 21, 22, 23, 24, 25]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.version }}
      - run: sudo apt-get update && sudo apt-get install libcpputest-dev cpputest
      - run: npm i --ignore-scripts
      - run: npm run test:asan
      - run: npm run test:js-asan

  build:
    needs: ['cpp-lint', 'js-lint']
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@d4e89247e6dd34f485c0f92c12f0cc739c2f8c92 # main
    with:
      cache: false
      napi: false
      package-manager: 'npm'
      prebuild: 'node scripts/prebuild'
      skip: 'linux-arm,linux-ia32'
      target-name: 'iastnativemethods'
      min-node-version: 18

  cpp-test-libc:
    needs: ['build']
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        debian:
          - tag: testing
        target:
          - dockerfile: Dockerfile
            libc: libc
            artifact: linux-x64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - run: docker build -t cpputest-libc --build-arg TAG=${{ matrix.debian.tag }} -f ./docker/${{ matrix.target.dockerfile }} .
      - run: docker run --name test-libc cpputest-libc
      - run: docker cp test-libc:/build/test/cpputest/results/ .
      - uses: mikepenz/action-junit-report@150e2f992e4fad1379da2056d1d1c279f520e058 # v3.8.0
        if: always()
        with:
          report_paths: '**/results/cpputest_*.xml'
          check_name: junit test report ${{ matrix.target.name }}

  cpp-test-musl:
    needs: ['build']
    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        alpine:
          - tag: latest
        target:
          - dockerfile: alpine.Dockerfile
            libc: musl
            artifact: linuxmusl-x64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: true
      - run: docker build -t cpputest-musl --build-arg TAG=${{ matrix.alpine.tag }} -f ./docker/${{ matrix.target.dockerfile }} .
      - run: docker run --name test-musl cpputest-musl
      - run: docker cp test-musl:/build/test/cpputest/results/ .
      - uses: mikepenz/action-junit-report@150e2f992e4fad1379da2056d1d1c279f520e058 # v3.8.0
        if: always()
        with:
          report_paths: '**/results/cpputest_*.xml'
          check_name: junit test report ${{ matrix.target.name }}

  cpp-lint:
    needs: ['check-licenses']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
      - run: pip install cpplint
      - run: cpplint --filter=-build/include_subdir,-whitespace/indent_namespace --linelength=120 --recursive ./src

  js-lint:
    needs: ['check-licenses']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20'
      - run: npm i --ignore-scripts
      - run: npm run lint

  check-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '20'
      - run: npm i --ignore-scripts
      - run: node scripts/check_licenses.js

  pack:
    needs: ['cpp-test-musl', 'cpp-test-libc']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      - run: npm pack
      - uses: codex-team/action-nodejs-package-info@ff87ea62824a9084fdf0676ea83e2865de6249f1 # v1.0.0
        id: package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: datadog-native-iast-taint-tracking-${{ steps.package.outputs.version }}
          path: '*.tgz'

  test-native-js:
    needs: ['pack']
    strategy:
      matrix:
        target:
          - name: linux 64 bits
            os: ubuntu-latest
            artifact: linux-x64-gnu
          - name: windows 64 bits
            os: windows-2022
            artifact: win32-x64-msvc
          - name: macos 64 bits
            os: macos-latest
            artifact: darwin-x64

    runs-on: ${{ matrix.target.os }}
    permissions:
      checks: write
    env:
      NPM_TAINTEDUTILS: true
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18'
      - run: npm ci --ignore-scripts
      - run: npm install node-gyp
      - uses: codex-team/action-nodejs-package-info@ff87ea62824a9084fdf0676ea83e2865de6249f1 # v1.0.0
        id: package
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: datadog-native-iast-taint-tracking-${{ steps.package.outputs.version }}
      - run: npm i --verbose datadog-native-iast-taint-tracking-${{ steps.package.outputs.version }}.tgz
      - run: npm run test:js-junit
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@150e2f992e4fad1379da2056d1d1c279f520e058 # v3.8.0
        if: always()
        with:
          report_paths: '**/build/junit.xml'
          check_name: junit test report ${{ matrix.target.name }}

  all-good:
    needs:
      - test-native-js
    runs-on: ubuntu-latest
    steps:
      - run: echo '🚀🚀🚀🚀🚀'

