name: Release

on:
  push:
    branches:
      - v[0-9]+.x

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      cache: false
      napi: false
      package-manager: 'npm'
      prebuild: 'node scripts/prebuild'
      skip: 'linux-arm linux-ia32'
      target-name: 'iastnativemethods'

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: npm
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
      - uses: codex-team/action-nodejs-package-info@v1.1
        id: package
      - run: |
          git tag v${{ steps.package.outputs.version }}
          git push origin v${{ steps.package.outputs.version }}
